AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: 's3://codepipeline-us-west-1-403904336812/HelloServiceCodepipe/SourceArti/1c7Vpv6.zip'
      Stages:
          Actions:
              Configuration:
                Capabilities: [CAPABILITY_AUTO_EXPAND]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
